apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Chart.Name }}-configmap

data:
    application.yaml: |
        server:
            port: 8082
            compression:
                enabled: true
                mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
                min-response-size: 1024
            servlet:
                session:
                    cookie:
                        http-only: true
                context-path: /pep/restaurant/manager
        spring:
            datasource:
                type: com.zaxxer.hikari.HikariDataSource
                url: "{{ .Values.app.properties.db_url}}"
                username: "{{ .Values.app.properties.db_username}}"
                password: "{{ .Values.app.properties.db_password}}"
                driver-class-name: "{{ .Values.app.properties.db_driver}}"
                hikari:
                    poolName: Hikari
                    maximumPoolSize: 10
                    auto-commit: false
            jpa:
                show-sql: false
            liquibase:
                change-log: classpath:/db.changelog/changelog-master.xml