apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: "{{ .Chart.Name }}-ingress"
    labels:
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        stage: {{ .Values.app.properties.environment }}
        app: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: {{ .Values.image.tag | default .Chart.AppVersion }}
        app.kubernetes.io/part-of: APP
        app.kubernetes.io/managed-by: Helm
    annotations:
        kubernetes.io/ingress.class: private-nginx
        nginx.ingress.kubernetes.io/backend-protocol: HTTP
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
    tls:
        -   hosts:
                - "{{ .Chart.Name }}.{{ .Values.app.properties.content }}.{{ .Values.app.properties.environment }}"
                - "{{ .Chart.Name }}-{{ .Values.app.properties.content }}-{{ .Values.app.properties.environment }}"
            secretName: {{ .Chart.Name }}-tls
    rules:
        -   host: "{{ .Chart.Name }}.{{ .Values.app.properties.content }}.{{ .Values.app.properties.environment }}"
            http:
                paths:
                    -   path: /
                        pathType: ImplementationSpecific
                        backend:
                            service:
                                name: {{ .Chart.Name }}
                                port:
                                    number: {{ .Values.service.port }}